export const ODDULAR_STOREFRONT_TOKEN =
  process.env.NEXT_PUBLIC_ODDULAR_STOREFRONT_TOKEN;

export const ODDULAR_STOREFRONT_GRAPHQL_ENDPOINT =
  process.env.NEXT_PUBLIC_ODDULAR_STOREFRONT_GRAPHQL_ENDPOINT;
